# Generated by Django 4.1.7 on 2023-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1000),
        ),
    ]
